config/routes.rb
Rails.application.routes.draw do

  # get 'admin/tools'
  resources :works
  match '/admin/tools', :to => "admin#tools", :as => :admin_tools, via: [:get, :post]

  root to: 'static#index'
  
  devise_for :users, controllers: {sessions: 'users/sessions'}

  match '/work/:page', :to => "static#work", :as => :work_page, via: [:get, :post]
  match '/create', :to => "admin#create", :as => :create, via: [:get, :post]
  # match '/work_create', :to => "works#create", :as => :work, via: [:get, :post]
  # match '/form/new', :to => "works#new", :as => :new_work, via: [:get, :post]
  match '/addimage', :to => "works#addimage", :as => :addimage, via: [:get, :post]
  match '/del_image', :to => "works#del_image", :as => :del_image, via: [:get, :post]
  # match '/work/delete', :to => "works#delete", :as => :delete, via: [:get, :post, :delete]
  # match '/work/:id', :to => "works#edit", :as => :edit, via: [:get, :post, :put]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # match '/admin/tools', :to => "admin_tools#admin", :as => :admin_tools, via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "50x50#", icon: "70x70#", midle: "700x510#"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "ladmin"
  
  def tools
  
    @work = Work.all

  end

  def create

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    admin_tools_path
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  
  def index
    @idwork = Work.all
  end

  def work
    @text = params[:page]
    @imagework = Work.find(params[:page])
    render :layout => false
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

#   GET /resource/sign_in
#   def new
#     super
#   end

#   POST /resource/sign_in
  # def create
  #   super
  # end

#   DELETE /resource/sign_out
#   def destroy
#     super
#   end

#   protected

#   If you have extra params to permit, append them to the sanitizer.
#   def configure_sign_in_params
#     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
#   end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:delete, :edit, :update, :destroy]
  layout "ladmin"

  def new
    @game = Work.new
  end

  def create
    Work.create(work_params)
    redirect_to "/admin/tools"
  end

  def addimage
    puts params.inspect
  end

  def edit
    @game = @work
  end

  def update
    @work.update(work_params)
    redirect_to "/admin/tools"
  end

  def destroy
    @work.destroy
    redirect_to "/admin/tools"
  end
  
  def del_image
    @id = params[:image][:id]
    Image.find(@id).delete
  end
  
  private

  def work_params
    params.require(:work).permit(:name, :description, images_attributes: [:image])
  end

  def set_work
    @work = Work.find(params[:id])
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/_form.html.haml
%br
%br
%br
%br
%br
%section.container
  .row-fluid  
    .button-box.section-emphasis-2  
      = form_for(:user, :url => session_path(:user), :html => { :class => 'navbar-form pull-left' }) do |f|
        
        = f.text_field :email, placeholder: "email"
        = f.password_field :password, placeholder: "Password", autocomplete: "off"
        = f.button :submit, :class => 'btn'
    / = link_to t('.cancel', :default => t("helpers.links.cancel")), bots_path, :class => 'btn btn-default'
  

app/views/admin/tools.html.haml
%br
%br
%br
%section.container 
  .row-fluid
    .table-special
      %table
        %thead
          %tr
            %td
              Header 1
            %td
              Описание
            %td
              Header 3
            %td
              Header 4
        %tbody
          - @work.each do |work|
            %tr
              %td
                = work[:name]
              %td
                = work[:description][0..19]
                %p
                = work.description.length > 40 ? work[:description][20..37] + "..." : work[:description]
              %td
                Nov 12, 2013
              %td
                = link_to "delete", work_path(id: work.id),method: :delete, data: {confirm: "Вы уверены, что хотите удалить игру?"}, class: "btn btn-danger btn-mini"
                = link_to "edit", edit_work_path(work), remote: true, class: "btn btn-warning btn-mini"
      %br
      = link_to "New", new_work_path, remote: true, class: "btn btn-success pull-right"
.modal.hide.fade#modal
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3 Заполните Форму
  .modalnew
.modal.hide.fade#edit
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3 Предупреждение
  .modaledit 
:css
  #textcolor{
    color: #08c;
  }

app/views/layouts/_footer.html.haml
%footer
  / .container
  /   .row-fluid
  /     .span3
  /       .text-widget.widget
  /         %h4 About nonus
  /         %p
  /           Lorem ipsum dolor nonus amet, consectetur ex adipisicing elit, sed do eiusmod incididunt ut labore et
  /           dolore magna aliqua. Ut enim ad ex minim veniam, quis nostrud lorem exercitation ullamco laboris
  /           nisi ut aliquip nesciunt aliqua.
  /     .span3
  /       .latest-posts-widget.widget
  /         %h4 Latest posts
  /         %ul.latest-posts.latest-posts-widget
  /           %li
  /             %span.title
  /               %a{:href => "03-blog-single.html"} Standard Post Format with Image
  /             %span.date Aug 1, 2013
  /           %li
  /             %span.title
  /               %a{:href => "03-blog-single.html"} Gallery Post Format
  /             %span.date Jul 29, 2013
  /           %li
  /             %span.title
  /               %a{:href => "03-blog-single.html"} Link Post Format
  /             %span.date Jul 22, 2013
  /     .span3
  /       .photo-stream-widget.widget
  /         %h4 Photo stream
  /         .flickr_badge
  /           .flickr_badge_image
  /             %a{:href => "#"}
  /               %img{:alt => "", :src => "images/content/works/thumbnails/work-thumbnail-1.jpg"}/
  /           .flickr_badge_image
  /             %a{:href => "#"}
  /               %img{:alt => "", :src => "images/content/works/thumbnails/work-thumbnail-2.jpg"}/
  /           .flickr_badge_image
  /             %a{:href => "work3.html"}
  /               %img{:alt => "", :src => "images/content/works/thumbnails/work-thumbnail-3.jpg"}/
  /           .flickr_badge_image
  /             %a{:href => "work4.html"}
  /               %img{:alt => "", :src => "images/content/works/thumbnails/work-thumbnail-4.jpg"}/
  /           .flickr_badge_image
  /             %a{:href => "work5.html"}
  /               %img{:alt => "", :src => "images/content/works/thumbnails/work-thumbnail-5.jpg"}/
  /           .flickr_badge_image
  /             %a{:href => "work6.html"}
  /               %img{:alt => "", :src => "images/content/works/thumbnails/work-thumbnail-6.jpg"}/
      
  / %h4 GCGAMES

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="shortcut icon" href="favicon.ico">

    <title>Nonus - One Page Parallax HTML5/CSS3 Template</title>

    <!-- <link rel="stylesheet" type="text/css" href="assets/stylesheets/style.css"> -->
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    

    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <![endif]-->

    <!-- conditional IE styles -->
    <!--[if IE]>
    <link rel="stylesheet" type="text/css" href="css/ie.css"/>
    <![endif]-->
    <style>
    </style>
</head>
<body data-spy="scroll" data-target="#MainNav" data-offset="74">
<%= yield %>
<%= render "layouts/footer" %>

</div>

<!-- javascript -->


</body>
</html>

app/views/layouts/ladmin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
    %link{:href => "favicon.ico", :rel => "shortcut icon"}
    %title Nonus - One Page Parallax HTML5/CSS3 Template
    / <link rel="stylesheet" type="text/css" href="assets/stylesheets/style.css">
    = javascript_include_tag "application"
    = csrf_meta_tag
    = stylesheet_link_tag "application", :media => "all"
%nav#MainNav.navbar.sticky
  %a.arrow{:href => "#MainNav"}
  .navbar-inner
    .container
      %button.btn.btn-navbar.collapsed{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
        / This button toggles visibility of menu on mobile devices
      %a.brand{:href => "#MainHeader"}
        %img{:alt => "companyname", :src => "/images/logo-small.png"}
      -if current_user
        .nav-collapse.collapse
          %ul.nav.nav-pills
            %li.dropdown
              %a.dropdown-toggle{:href => root_path} Home
            %li
              = link_to "выход #{current_user.email}", destroy_user_session_path
      -else
-if current_user
  = yield
-else
  =render "form"

app/views/works/_formwork.html.haml
.modal-body
  .row-fluid  
    .button-box.section-emphasis-2  
      = form_for(@game, :html => { :class => 'navbar-form', :multipart => true }) do |f|
        %h4#textcolor Название
        = f.text_field :name
        %h4#textcolor Описание
        = f.text_field :description
        
        #photo
        #end
        = f.button :submit, :class => 'btn'
        = link_to "Добавить картинку", addimage_path, remote: true, class: "btn btn-success pull-right"
.modal-footer
  %ul.thumbnails  
    -if @game.name.nil? 
    -else  
      - @game.images.each do |p|
        %li{id: "image_" + p.id.to_s}   
          = form_for(p, url: "/del_image", method: "get", remote: true) do |s|   
            = s.hidden_field :id, value: p.id
            .image_container  
              = s.submit "", class: "image_submit"
              = image_tag p.image.url(:icon)   
/ %ul.thumbnails
:css
  .image_submit{
    background:url("../images/close.png") !important;
    background-repeat: no-repeat !important;
    width: 27px !important;
    height: 27px !important;
    padding: 0 !important;
    margin: 0 !important;
    position: relative !important;
    top: 25px;
    left: 24px;
  } 
  .image_container{
    width: 70px !important;
    height: 70px !important;
    padding: 0 !important;
    display: inline !important;
  }
  .edit_image{
    width: 70px !important;
    height: 70px !important;
    padding: 0 !important;
  }

app/views/works/addimage.js.erb
var size = $('.file_field').length;
var imgsize = $('form.edit_image').length;
if (size < (6 - imgsize) && imgsize < 6){
  $("#photo").append("<h4 id = 'textcolor'>Добавьте картинку</h4><input type='file' name='work[images_attributes][" + size.toString() + "][image]' id='work_images_attributes_" + size.toString() + "_image' class = 'file_field'>");
}else{
  $("#end").html("<h4 id = 'textcolor'>Максимальное количество картинок</h4>");
}

app/views/works/del_image.js.erb
alert("#image_" + "<%= @id %>");
$("#image_" + "<%= @id %>").remove();

app/views/works/edit.js.erb
$(".modaledit").html("");
$(".modalnew").html("");
$(".modaledit").html("<%= j render('formwork') %>");
$("#edit").modal("show");

app/views/works/new.js.erb
$(".modalnew").html("");
$(".modaledit").html("");
$(".modalnew").html("<%= j render('formwork') %>");
$("#modal").modal("show");